# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#male_actors
# Contestant.create(name: "Henry Cavill", role: "actor", media: "The Witcher")
# Contestant.create(name: "James Marsden", role: "actor", media: "Enchanted")
# Contestant.create(name: "Robert Pattinson", role: "actor", media: "Twilight")
# Contestant.create(name: "Chris Evans", role: "actor", media: "Captain America")
# Contestant.create(name: "Chris Pratt", role: "actor", media: "Guardians of the Galaxy")
# Contestant.create(name: "Chris Pine", role: "actor", media: "Wonder Woman")
# Contestant.create(name: "Chris Hemsworth", role: "actor", media: "Thor")
# Contestant.create(name: "Michael B. Jordan", role: "actor", media: "Black Panther")
# Contestant.create(name: "Zac Efron", role: "actor", media: "High School Musical")
# Contestant.create(name: "Idris Elba", role: "actor", media: "The Wire")
# Contestant.create(name: "Daniel Henney", role: "actor", media: "Game of Thrones")
# Contestant.create(name: "Keanue Reeves", role: "actor", media: "Game of Thrones")
# Contestant.create(name: "Christian Bale", role: "actor", media: "American Psycho")
# Contestant.create(name: "Winston Duke", role: "actor", media: "Black Panther")
# Contestant.create(name: "Sebastian Stan", role: "actor", media: "Captain America")
# Contestant.create(name: "Ryan Reynolds", role: "actor", media: "Deadpool")
# Contestant.create(name: "Ryan Gosling", role: "actor", media: "The Notebook")
# Contestant.create(name: "Chace Crawford", role: "actor", media: "Gossip Girl")
# Contestant.create(name: "Chad Michael Murray", role: "actor", media: "A Cinderella Story")
# Contestant.create(name: "Ed Westwick", role: "actor", media: "Gossip Girl")
# Contestant.create(name: "Orlando Bloom", role: "actor", media: "Lord of the Rings")
# Contestant.create(name: "Penn Badgley", role: "actor", media: "Gossip Girl")
# Contestant.create(name: "Adam Brody", role: "actor", media: "The O.C.")

#idols

# Contestant.create(name: "Bang Chan", role: "idol", group: "Stray Kids")
# Contestant.create(name: "Lee Know", role: "idol", group: "Stray Kids")
# Contestant.create(name: "Changbin", role: "idol", group: "Stray Kids")
# Contestant.create(name: "Han", role: "idol", group: "Stray Kids")
# Contestant.create(name: "Felix", role: "idol", group: "Stray Kids")
# Contestant.create(name: "Hyunjin", role: "idol", group: "Stray Kids")
# Contestant.create(name: "IN", role: "idol", group: "Stray Kids")

# Contestant.create(name: "Jun.K", role: "idol", group: "2PM")
# Contestant.create(name: "Nichkhun", role: "idol", group: "2PM")
# Contestant.create(name: "Taecyeon", role: "idol", group: "2PM")
# Contestant.create(name: "Wooyoung", role: "idol", group: "2PM")
# Contestant.create(name: "Chansung", role: "idol", group: "2PM")
# Contestant.create(name: "Junho", role: "idol", group: "2PM")

# Contestant.create(name: "RM", role: "idol", group: "BTS")
# Contestant.create(name: "Jungkook", role: "idol", group: "BTS")
# Contestant.create(name: "J.Hope", role: "idol", group: "BTS")
# Contestant.create(name: "Taehyung", role: "idol", group: "BTS")
# Contestant.create(name: "Jin", role: "idol", group: "BTS")
# Contestant.create(name: "Suga", role: "idol", group: "BTS")
# Contestant.create(name: "Jimin", role: "idol", group: "BTS")

# Contestant.create(name: "Onew", role: "idol", group: "SHINee")
# Contestant.create(name: "Minho", role: "idol", group: "SHINee")
# Contestant.create(name: "Key", role: "idol", group: "SHINee")
# Contestant.create(name: "Taemin", role: "idol", group: "SHINee")
# Contestant.create(name: "Jonghyun", role: "idol", group: "SHINee")

# Contestant.create(name: "Winwin", role: "idol", group: "WayV")
# Contestant.create(name: "Lucas", role: "idol", group: "WayV")
# Contestant.create(name: "Ten", role: "idol", group: "WayV")
# Contestant.create(name: "Yangyang", role: "idol", group: "WayV")
# Contestant.create(name: "Hendery", role: "idol", group: "WayV")
# Contestant.create(name: "Xiaojun", role: "idol", group: "WayV")
# Contestant.create(name: "Kun", role: "idol", group: "WayV")

# Contestant.create(name: "Taemin", role: "idol", group: "SuperM")
# Contestant.create(name: "Baekhyun", role: "idol", group: "SuperM")
# Contestant.create(name: "Lucas", role: "idol", group: "SuperM")
# Contestant.create(name: "Kai", role: "idol", group: "SuperM")
# Contestant.create(name: "Ten", role: "idol", group: "SuperM")
# Contestant.create(name: "Taeyong", role: "idol", group: "SuperM")
# Contestant.create(name: "Mark", role: "idol", group: "SuperM")

# Contestant.create(name: "Ryukin", role: "idol", group: "Itzy")
# Contestant.create(name: "Lia", role: "idol", group: "Itzy")
# Contestant.create(name: "Chaeryeong", role: "idol", group: "Itzy")
# Contestant.create(name: "Yeji", role: "idol", group: "Itzy")
# Contestant.create(name: "Yuna", role: "idol", group: "Itzy")

# Contestant.create(name: "Jihyo", role: "idol", group: "TWICE")
# Contestant.create(name: "Nayeon", role: "idol", group: "TWICE")
# Contestant.create(name: "Momo", role: "idol", group: "TWICE")
# Contestant.create(name: "Sana", role: "idol", group: "TWICE")
# Contestant.create(name: "Mina", role: "idol", group: "TWICE")
# Contestant.create(name: "Dahyun", role: "idol", group: "TWICE")
# Contestant.create(name: "Chaeyoung", role: "idol", group: "TWICE")
# Contestant.create(name: "Jeongyeon", role: "idol", group: "TWICE")
# Contestant.create(name: "Tzuyu", role: "idol", group: "TWICE")

# Contestant.create(name: "Lisa", role: "idol", group: "BlackPink")
# Contestant.create(name: "Jisoo", role: "idol", group: "BlackPink")
# Contestant.create(name: "Rose", role: "idol", group: "BlackPink")
# Contestant.create(name: "Jennie", role: "idol", group: "BlackPink")

# Contestant.create(name: "Yoohyeon", role: "idol", group: "Dreamcatcher")
# Contestant.create(name: "SuA", role: "idol", group: "Dreamcatcher")
# Contestant.create(name: "JiU", role: "idol", group: "Dreamcatcher")
# Contestant.create(name: "Handong", role: "idol", group: "Dreamcatcher")
# Contestant.create(name: "Dami", role: "idol", group: "Dreamcatcher")
# Contestant.create(name: "Gahyeon", role: "idol", group: "Dreamcatcher")
# Contestant.create(name: "Siyeon", role: "idol", group: "Dreamcatcher")

# Contestant.create(name: "Aisha", role: "idol", group: "Everglow")
# Contestant.create(name: "Onda", role: "idol", group: "Everglow")
# Contestant.create(name: "E:U", role: "idol", group: "Everglow")
# Contestant.create(name: "Yiren", role: "idol", group: "Everglow")
# Contestant.create(name: "Mia", role: "idol", group: "Everglow")
# Contestant.create(name: "Si-hyeon", role: "idol", group: "Everglow")

# Contestant.create(name: "Jessica", role: "idol", group: "SNSD")
# Contestant.create(name: "Tiffany", role: "idol", group: "SNSD")
# Contestant.create(name: "Sunny", role: "idol", group: "SNSD")
# Contestant.create(name: "Yuri", role: "idol", group: "SNSD")
# Contestant.create(name: "Yoona", role: "idol", group: "SNSD")
# Contestant.create(name: "Hyoyeon", role: "idol", group: "SNSD")
# Contestant.create(name: "Sooyoung", role: "idol", group: "SNSD")
# Contestant.create(name: "Seohyun", role: "idol", group: "SNSD")
# Contestant.create(name: "Tayeon", role: "idol", group: "SNSD")

#books
