# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# #male_actors
# Actor.create(name: "Henry Cavill", known_for: "The Witcher")
# Actor.create(name: "James Marsden", known_for: "Enchanted")
# Actor.create(name: "Robert Pattinson", known_for: "Twilight")
# Actor.create(name: "Chris Evans", known_for: "Captain America")
# Actor.create(name: "Chris Pratt", known_for: "Guardians of the Galaxy")
# Actor.create(name: "Chris Pine", known_for: "Wonder Woman")
# Actor.create(name: "Chris Hemsworth", known_for: "Thor")
# Actor.create(name: "Michael B. Jordan", known_for: "Black Panther")
# Actor.create(name: "Zac Efron", known_for: "High School Musical")
# Actor.create(name: "Idris Elba", known_for: "The Wire")
# Actor.create(name: "Daniel Henney", known_for: "Game of Thrones")
# Actor.create(name: "Keanue Reeves", known_for: "Game of Thrones")
# Actor.create(name: "Christian Bale", known_for: "American Psycho")
# Actor.create(name: "Winston Duke", known_for: "Black Panther")
# Actor.create(name: "Sebastian Stan", known_for: "Captain America")
# Actor.create(name: "Ryan Reynolds", known_for: "Deadpool")
# Actor.create(name: "Ryan Gosling", known_for: "The Notebook")
# Actor.create(name: "Chace Crawford", known_for: "Gossip Girl")
# Actor.create(name: "Chad Michael Murray", known_for: "A Cinderella Story")
# Actor.create(name: "Ed Westwick", known_for: "Gossip Girl")
# Actor.create(name: "Orlando Bloom", known_for: "Lord of the Rings")
# Actor.create(name: "Penn Badgley", known_for: "Gossip Girl")
# Actor.create(name: "Adam Brody", known_for: "The O.C.")

# #idols

# Idol.create(name: "Bang Chan", position: "leader", group: "Stray Kids")
# Idol.create(name: "Lee Know", position: "main dancer", group: "Stray Kids")
# Idol.create(name: "Changbin", position: "main rapper", group: "Stray Kids")
# Idol.create(name: "Han", position: "main vocal", group: "Stray Kids")
# Idol.create(name: "Felix", position: "idol", group: "Stray Kids")
# Idol.create(name: "Hyunjin", position: "visual", group: "Stray Kids")
# Idol.create(name: "IN", position: "maknae", group: "Stray Kids")

# Idol.create(name: "Jun.K", position: "leader", group: "2PM")
# Idol.create(name: "Nichkhun", group: "2PM")
# Idol.create(name: "Taecyeon", position: "rapper", group: "2PM")
# Idol.create(name: "Wooyoung", group: "2PM")
# Idol.create(name: "Chansung", position: "maknae", group: "2PM")
# Idol.create(name: "Junho", group: "2PM")

# Idol.create(name: "RM", position: "leader", group: "BTS")
# Idol.create(name: "Jungkook", position: "maknae", group: "BTS")
# Idol.create(name: "J.Hope", group: "BTS")
# Idol.create(name: "Taehyung", group: "BTS")
# Idol.create(name: "Jin", group: "BTS")
# Idol.create(name: "Suga", group: "BTS")
# Idol.create(name: "Jimin", group: "BTS")

# Idol.create(name: "Onew", position: "leader", group: "SHINee")
# Idol.create(name: "Minho", position: "rapper", group: "SHINee")
# Idol.create(name: "Key", group: "SHINee")
# Idol.create(name: "Taemin", position: "maknae", group: "SHINee")
# Idol.create(name: "Jonghyun", position: "lead vocal", group: "SHINee")

# Idol.create(name: "Winwin", group: "WayV")
# Idol.create(name: "Lucas", group: "WayV")
# Idol.create(name: "Ten", group: "WayV")
# Idol.create(name: "Yangyang", group: "WayV")
# Idol.create(name: "Hendery", group: "WayV")
# Idol.create(name: "Xiaojun", group: "WayV")
# Idol.create(name: "Kun", group: "WayV")

# Idol.create(name: "Taemin", group: "SuperM")
# Idol.create(name: "Baekhyun", group: "SuperM")
# Idol.create(name: "Lucas", group: "SuperM")
# Idol.create(name: "Kai", group: "SuperM")
# Idol.create(name: "Ten", group: "SuperM")
# Idol.create(name: "Taeyong", group: "SuperM")
# Idol.create(name: "Mark", group: "SuperM")

# Idol.create(name: "Ryukin", group: "Itzy")
# Idol.create(name: "Lia", group: "Itzy")
# Idol.create(name: "Chaeryeong", group: "Itzy")
# Idol.create(name: "Yeji", group: "Itzy")
# Idol.create(name: "Yuna", group: "Itzy")

# Idol.create(name: "Jihyo", position: "leader", group: "TWICE")
# Idol.create(name: "Nayeon", group: "TWICE")
# Idol.create(name: "Momo", group: "TWICE")
# Idol.create(name: "Sana", group: "TWICE")
# Idol.create(name: "Mina", group: "TWICE")
# Idol.create(name: "Dahyun", group: "TWICE")
# Idol.create(name: "Chaeyoung", group: "TWICE")
# Idol.create(name: "Jeongyeon", group: "TWICE")
# Idol.create(name: "Tzuyu", group: "TWICE")

# Idol.create(name: "Lisa", group: "BlackPink")
# Idol.create(name: "Jisoo", group: "BlackPink")
# Idol.create(name: "Rose", group: "BlackPink")
# Idol.create(name: "Jennie", group: "BlackPink")

# Idol.create(name: "Yoohyeon", group: "Dreamcatcher")
# Idol.create(name: "SuA", group: "Dreamcatcher")
# Idol.create(name: "JiU", group: "Dreamcatcher")
# Idol.create(name: "Handong", group: "Dreamcatcher")
# Idol.create(name: "Dami", group: "Dreamcatcher")
# Idol.create(name: "Gahyeon", group: "Dreamcatcher")
# Idol.create(name: "Siyeon", group: "Dreamcatcher")

# Idol.create(name: "Aisha", group: "Everglow")
# Idol.create(name: "Onda", group: "Everglow")
# Idol.create(name: "E:U", group: "Everglow")
# Idol.create(name: "Yiren", group: "Everglow")
# Idol.create(name: "Mia", group: "Everglow")
# Idol.create(name: "Si-hyeon", group: "Everglow")

# Idol.create(name: "Jessica", group: "SNSD")
# Idol.create(name: "Tiffany", group: "SNSD")
# Idol.create(name: "Sunny", group: "SNSD")
# Idol.create(name: "Yuri", group: "SNSD")
# Idol.create(name: "Yoona", position: "visual", group: "SNSD")
# Idol.create(name: "Hyoyeon", group: "SNSD")
# Idol.create(name: "Sooyoung", group: "SNSD")
# Idol.create(name: "Seohyun", position: "maknae", group: "SNSD")
# Idol.create(name: "Tayeon", position: "leader", group: "SNSD")

# #tropes

# Trope.create(title: "The Grumpy One is soft for the Sunshine One.")
# Trope.create(title: "The CEO and their Secretary.")
# Trope.create(title: "Arranged Marriage.")
# Trope.create(title: "Calls each other by title or last name until one of them gets sick or in danger and then they use their real name.")
# Trope.create(title: "They are roommates.")
# Trope.create(title: "The Reserved One, who doesn't express themselves, smiles when their Love Interest does something cute.")
# Trope.create(title: "They are archenemies who see each other as their equal.")
# Trope.create(title: "When One confesses to the other while they are sleeping but the Other One is awake to hear it.")
# Trope.create(title: "Dense meets Denser and everyone knows they're in love except them.")
# Trope.create(title: "One has Chronic Insomnia and can only sleep when Love Interest is in the same bed.")
# Trope.create(title: "Fake Relationship.")
# Trope.create(title: "One is Alive and One is Dead.")
# Trope.create(title: "Friends with Benefits.")
# Trope.create(title: "Enemies to Lovers.")
# Trope.create(title: "One is a Celebrity and the other is not.")
# Trope.create(title: "In Love, but One is their best friend's sibling.")
# Trope.create(title: "The Assassin and the One They Must Kill.")
# Trope.create(title: "The Loner and the Popular one.")
# Trope.create(title: "Soulmates like Red String of Fate.")
# Trope.create(title: "Actual Unrequited Love")
# Trope.create(title: "One of them dies.")
# Trope.create(title: "One of them ALMOST dies.")
